### ISSUE TITLE
Sidecar must run as privleged.

### ISSUE THREAD

**Issue by anoncam** [appgate/sdp-k8s-client#37]
I understand that for the current implementation of this sidecar the host interface needs to be accessible hence the container must run as a privileged container.

Is your team tracking that requirement still?

**Comment by anoncam** [comment]
I have rethought this. I'm closing the issue, but would like to discuss ways to handle the entitlement using L7.

**Comment by lepiolet** [comment]
@anoncam maybe you are interested in https://github.com/appgate/sdp-k8s-client/pull/61 and https://github.com/appgate/sdp-k8s-client/pull/65

Those reduce the permissions in the sidecars injected. All the services are running now as non-privileged users.
